### DISCUSSION TITLE
Using Build context to fetch a private image from GHCR

### DISCUSSION THREAD

**Discussion by OttoHung** [docker/buildx#1227] [Q&A]
Hi,
 I experimented to understand how `Buildx` uses the `--build-context` flag to fetch a private docker image from GHCR. Then I found `Buildx` can download the docker image from GHCR without being configured with any access token. I wonder how `Buildx` fetches a private docker image?

Also, I use `--build-context` to fetch a private git repository from GitHub and `Buildx` encounters the authentication issue as expected.

I saw two different behaviours by accessing the private registry and repository so I would like to know if this is common and how it makes it.

My test script is [here](https://github.com/OttoHung/docker.tutorials/blob/main/scripts/build-contexts/docker-image/build_from_private_registry.sh) and the private docker image is [here](https://github.com/OttoHung/private-test/pkgs/container/private-test).

Please feel free to let me know if this is an appropriate question. Thank you very much.

Have a good one.

> Note: 
> The `private docker image` means the visibility of this image is `private` on GHCR. 
> I did the test of removing PAT from ~/.npmrc then `Buildx` still can fetch the private docker image.

**Comment by jedevc** [comment]
Buildx will fetch your private image from GHCR if your `.docker/config.json` is configured with authentication credentials or a credentials helper to allow pulling from GHCR. This is pretty much identical to the mechanism used to do a `docker pull`.

I've answered the git repository question in the other discussion you opened [here](https://github.com/docker/buildx/discussions/1228)

**Reply by OttoHung** [reply]
Hi @jedevc ,
Thank you for the quick reply. I didn't configure .docker/config.json file in my local project folder, but I can find it  at `~/.docker`.

I just cat this file, it looks like there is no authentication credential configured as following:
```json
{
  "auths": {
    "ghcr.io": {}
  },
  "credsStore": "desktop"
}
```

Are there other places that could have the crednetial? From my understanding, I configured `~/.npmrc` to fetch npm packages from GitHub only.

**Reply by crazy-max** [reply]
Use `docker login ghcr.io` and it should be populated.

**Reply by OttoHung** [reply]
Hi @crazy-max,
Thank you for the reply. I used `docker login ghcr.io` with my PAT as `echo $TOKEN | docker login ghcr.io -u ottohung --password-stdin`. Then I got the same content by cating `~/.docker/config.json` as follows:
```json
{
        "auths": {
                "ghcr.io": {}
        },
        "credsStore": "desktop"
}
```

I use macOS for ths practice. Not quite sure what the problem is.

I tried to fetch private image and it works without `docker login`. If docker deamon uses docker CLI or other API to download the image, I think I may need to shoot this question to GitHub for declaration.

Thanks again.

Have a good one.

**Reply by wibed** [reply]
anyone found a way to force buildx to use available credentials

**Reply by zvi-quantivly** [reply]
Facing the same issue, can't get `buildx` to pull a private image from _ghcr.io_. 
My workflow includes:
```yaml
env:
  REGISTRY: "ghcr.io"
...
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
```
and the `build-push-action` includes:
```yaml
      - name: Build <org>/<repo>
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "${{ github.workspace }}/path/to/Dockerfile"
          build-contexts: |
            <base-reference>=${{ env.REGISTRY }}/<base-reference>
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
```
The `FROM` target in the `build-contexts` configuration (_ghcr.io/<org>/<repo>:<tag>_) is definitely built and pushed successfully, but I keep getting:
```bash
Error: buildx failed with: ERROR: failed to get build context <base-reference>: stat ghcr.io/<base-reference>: no such file or directory
```

I tried many things, including adding a manual `docker login ghcr.io` step to make sure _.docker/config.json_ is updated, but it didn't help.
Any help resolving this would be greatly appreciated.
