### ISSUE TITLE
Bake requires ports to be integer, but config outputs strings

### ISSUE THREAD

**Issue by janrito** [docker/buildx#1047]
context here: https://github.com/docker/compose/issues/9306

But essentially, 

```docker compose -f docker-compose.yml -f docker.compose.overrides.yml config```

will convert:
```yaml
services:
  service-name:
    ports:
    - "9000:9000"
```

into 
```yaml
services:
  service-name:
    ports:
    - mode: ingress
      protocol: tcp
      published: '9000'
      target: 9000
```

Which ill then cause: 
```
docker buildx bake -f docker-compose.resolved.yml
error: services.service-name.ports.0.published must be a integer
```
