### ISSUE TITLE
Option to only tag images at end of bake

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1089]
Currently `bake --push` will tag images in the remote registry as they are completed. This can be an issue if later images in the same high-level build error out.

Either the default behaviour could change, or a CLI option could be added that forces tagging to only happen at the end - I don't think pushing new layers would need to be held back.

This example results in a `foo` tag but not the `bar` one:

```Dockerfile
FROM alpine:3.15 as foo
FROM alpine:3.15 as bar
RUN sleep 30 && exit 1
```

```hcl
group "default" {
  targets = ["foo", "bar"]
}

target "foo" {
  target = "foo"
  tags = [
    "ciaranmcnulty/test:foo"
  ]
}

target "bar" {
  target = "bar"
  tags = [
    "ciaranmcnulty/test:bar"
  ]
}
```

**Comment by ciaranmcnulty** [comment]
This has come up today with `bake-action`, and I've ended up with this:

```yaml
      -
        name: Build 
        uses: docker/bake-action@master

      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
```

My issue is I `RUN` some tests at the end of the build and don't feel much need to do further testing before pushing, but if an individual image fails some may have already been pushed
