### ISSUE TITLE
Bake does not support `build.cache_to`

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1154]
[Compose-spec defines this field](https://github.com/compose-spec/compose-spec/blob/master/build.md#cache_to) but bake doesn't seem to see it

```yaml
services:
  web:
    build:
      context: .
      cache_to:
        - type=local,dest=path/to/cache
      cache_from:
        - type=local,dest=path/to/cache
```

is read as:

```json
{
  "group": {
    "default": {
      "targets": [
        "web"
      ]
    }
  },
  "target": {
    "web": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "cache-from": [
        "type=local,dest=path/to/cache"
      ]
    }
  }
```

This is maybe because `compose` doesn't really support it and bake uses the parser? It should really just be an alias or replacement for `build.x-bake.cache-to` I think?
