### ISSUE TITLE
Bake: Define project name and support COMPOSE_PROJECT_NAME in Yaml

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1161]
The [compose spec section about project names](https://github.com/compose-spec/compose-spec/blob/5260c1bc8ee5e93ce88412bb460924e9535d9080/spec.md#name-top-level-element) says:

> [the project name] MUST be exposed for [interpolation](https://github.com/docker/buildx/issues/new#interpolation) and environment variable resolution as COMPOSE_PROJECT_NAME

This would be pretty handy for one of my projects (to use as a tagging prefix)

Bake doesn't really have a way to define or compute the project name that I can see (I guess as it's not used for anything?) but it' suffice for me to read it from the `name:` top level element

```yaml
name: foo

services:
  myservice:
    build:
      x-bake:
        tags:
          - "${COMPOSE_PROJECT_NAME}"
```
Would be:
```json
"target": {
    "myservice": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "foo"
      ]
    }
  }

```
