### ISSUE TITLE
Bake does not allow or use tags from docker-compose.yml

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1187]
```yaml
services:

  test:
    build:
      tags:
        - my-test-tag
```

`docker compose build` will use this tag

`docker buildx bake`:

```
[+] Building 0.0s (0/0)                                                                                                                                                                                                                                                                                                 
error: services.test.build Additional property tags is not allowed
```
