### ISSUE TITLE
build-args doesn't resolve env vars

### ISSUE THREAD

**Issue by Craig1f** [docker/buildx#1302]
Summary: I need to pass a build-arg that is set dynamically.

Example: 

``` yaml

      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push with caching
        uses: docker/build-push-action@v3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: example
          IMAGE_TAG: pr-${{ github.event.number }}
          HELP_DESK_EMAIL_ADDRESS: fake@fake.fake
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:isolated-pr-${{ github.event.number }}
          target: serve-isolated
          build-args: |
            BUILD_DATE=${BUILD_DATE}
            HELP_DESK_EMAIL_ADDRESS="${HELP_DESK_EMAIL_ADDRESS"}
```

Result: Build date is equal to "${BUILD_DATE}" instead of being resolved into the value I set up in the previous action. Same issue happens with help desk email. 

Expected Behavior: ENV VARs set in GitHub Actions should resolve in build-args
