### ISSUE TITLE
multiarch build giving a plethora of errors when building for arm64

### ISSUE THREAD

**Issue by flixman** [docker/buildx#1405]
I have a github action that contains:

```yaml
jobs:
  build_publish_ansible_image:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          install: true
      ...
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker/ansible
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG}}:${{ env.VERSION }}
```

The correspondent docker file can be minimized to
```Dockerfile
FROM python:3.9-slim
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt-get -y install python3-minimal krb5-user libkrb5-dev
```

With this setup, from an amd64 machine, amd64 gets build without issues, but arm64 gets a full rainbow of them:
* dpkg-* binaries are expected in /usr/sbin, although they are in /usr/bin
* rm, tar are expected in /usr/sbin, although they are in /usr/bin
* nscd and sss_cache need to be manually installed, as suddenly they become dependencies

Should I build the same Dockerfile on an Apple M1 (linux/arm64), everything works out of the box... so seems this is a problem between buildx and qemu? Am I doing something terribly wrong, or there is something broken?

**Comment by rrooij** [comment]
Just curious, do you have the latest qemu action before you use the docker buildx action? I had similar issues until I added:

```


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

```

Before using the setup-buildx action.
