### ISSUE TITLE
Is it possible to save buildx's image as an image and push it to harbor through docker push or only through docker Buildx-Push to harbor

### ISSUE THREAD

**Issue by kubecto** [docker/buildx#1485]
Is it possible to save buildx's image as an image and push it to harbor through docker push or only through docker Buildx-Push to harbor

**Comment by crazy-max** [comment]
You can do

```console
$ docker buildx build -t user/repo:latest --load .
$ docker push user/repo:latest
```

Will not work with multi-platform images but if you are using Docker Desktop you can enable the containerd image store and it should work, see https://github.com/docker/roadmap/issues/371

**Comment by pplmx** [comment]
hi, @crazy-max 
After enable the containerd image store, it still does not work.

# Reproduce

## create buildx instance
```shell
docker buildx rm -f multiarch
docker buildx create --use --name multiarch --driver docker-container --config ./buildkitd.toml
```

buildkitd.toml

```toml
# insecure-entitlements allows insecure entitlements, disabled by default.
insecure-entitlements = [ "network.host", "security.insecure" ]

[registry."harbor.m.local"]
http = true
insecure = true
```

## build multiarch image
```shell
docker buildx build --load --platform linux/amd64,linux/arm64 -t harbor.m.local/cc/app .
```

## error

```txt
ERROR: docker exporter does not currently support exporting manifest lists
```
