### ISSUE TITLE
v0.10.0 "buildx create" fails with "ERROR [internal] booting buildkit"

### ISSUE THREAD

**Issue by maitredede** [docker/buildx#1536]
Hello,
I am trying to create builders with kubernetes driver.

The commandline looks like :
```
KUBECONFIG=~/.kube/config.custom.yml docker buildx create --bootstrap --name=thebuilder --config=buildkitd.toml --driver=kubernetes '--driver-opt="image=moby/buildkit:latest","namespace=mynamespace","nodeselector=kubernetes.io/arch=amd64"' --platform=linux/amd64 --node=builder-amd64 --use
```
With buildx version `v0.10.0` :
```
[+] Building 0.0s (1/1) FINISHED                                                                                                                                                                                   
 => ERROR [internal] booting buildkit                                                                                                                                                                         0.0s
------
 > [internal] booting buildkit:
------
thebuilder
```
With buildx version `v0.9.1`, it works (pod is created).

What can I do to gather informations ? (I have cloned the repo and can build from sources).

**Comment by AkihiroSuda** [comment]
Workaround: `docker buildx create` without `--use` and then bootstrap it

**Comment by AkihiroSuda** [comment]
Minimum repro:
```console
$ docker buildx create --bootstrap --name foo --driver=kubernetes  --driver-opt=namespace=mynamespace
[+] Building 0.1s (1/1) FINISHED                                                                                                                                                                                                                     
 => ERROR [internal] booting buildkit                                                                                                                                                                                                           0.1s
------
 > [internal] booting buildkit:
------
foo
```

It seems to work after `kubectl create namespace mynamespace`

**Comment by Hippskill** [comment]
I think I have similar problem
https://github.com/docker/cli/issues/3988

**Comment by crazy-max** [comment]
We have e2e tests for this but we might miss some cases: https://github.com/docker/buildx/actions/runs/3998235484/jobs/6860664656#step:10:16

We are setting up k3s: https://github.com/docker/buildx/actions/runs/3998235484/jobs/6860664656#step:7:69

> This occurs regardless of KUBECONFIG env var being exported or not. We were not exporting it, and placing it in the default location `~/.kube/config`.

Ok so looks to be a regression, will look at this.

**Comment by crazy-max** [comment]
The `KUBECONFIG` looks to be taken into account on my side and BuildKit is booting: https://github.com/docker/buildx/actions/runs/4002081140/jobs/6868992806#step:9:16

I also update to latest Kube 1.26.0 to be sure and looks good too: https://github.com/docker/buildx/actions/runs/4002081140/jobs/6868992806#step:7:79

Can someone gives a full repro, that would be handy.

Also can someone tries with `--driver-opt=moby/buildkit:v0.10.6` to be sure this is not linked to something we encounter on cli with containerd integration: https://github.com/docker/cli/issues/3982#issuecomment-1402051087

**Comment by ddelange** [comment]
private stuff removed: this workflow broke somewhere in the past 6 days.

adding `version: v0.9.1` to `docker/setup-buildx-action@v2` got us running again

```yaml
name: CD

on:
  workflow_dispatch:
  release:
    types: [prereleased, released]

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir ~/.kube && printf "$KUBECONFIG" >> ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - uses: docker/setup-buildx-action@v2
        with:
          driver: kubernetes
          driver-opts: |
            namespace=docker-registry
            replicas=1
            requests.cpu=1m
            limits.cpu=4
            limits.memory=3500Mi
            rootless=true
            nodeselector=kubernetes.io/arch=arm64
            "tolerations=key=arch,value=arm64,operator=Equal,effect=NoSchedule"

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # pragma: allowlist secret

      - name: Multi-arch Docker images
        uses: docker/bake-action@v2.2.0
        timeout-minutes: 15
        env:
          REPOSITORY_URI: ${{ github.repository }}
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          push: ${{ github.event_name == 'release' }}
          files: |
            docker-compose.yml
          set: |
            *.platform=linux/arm64
```
