### ISSUE TITLE
0.10.0 seeing "ERROR: httpReadSeeker: failed open: content not found" for multiarch manfiest

### ISSUE THREAD

**Issue by mtraynham** [docker/buildx#1555]
We have a multiarch build setup for AMD64 Ubuntu and ARM64 Ubuntu, and self-hosted Github runner deploying to our Github container registry.

Yesterday we started seeing the following during our builds:

> #42 merging manifest list ghcr.io/redacted:latest,ghcr.io/redacted:20230125004727Z-9965784,ghcr.io/redacted:9965784
#42 ERROR: httpReadSeeker: failed open: content at https://ghcr.io/v2/redacted/manifests/sha256:2105248bf12ff52de4cfc92124f85db53b788d675d546e1fefcfe13599350a79 not found: not found

The Github workflow actually succeeds and it seems like the Docker build didn't actually raise any exit codes other than 0.  However, the build silently fails to push to Github Container Registry.

I believe we started pulling in docker-ce 20.10.23 (https://docs.docker.com/engine/release-notes/#201023) yesterday which includes buildx 0.10.0.  A downgrade to docker-ce 20.10.22 seems to correct the issue.

I'm not 100% positive this bug is intended for buildx, as I don't fully know all the projects associated with Docker and where to report errors like this, but the Github Workflow utilizes a buildx step to do the build and push, this being where it fails silently.

```yaml
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.vars.outputs.iso_date }}
            BUILD_DATE_TAG=${{ steps.docker_vars.outputs.tag_date }}
            VCS_REF=${{ steps.vars.outputs.sha_short }}
            IMAGE_VERSION=${{ steps.docker_vars.outputs.tag_date }}-${{ steps.vars.outputs.sha_short }}
          push: true
          tags: |
            ${{ steps.vars.outputs.image_name }}:latest
            ${{ steps.vars.outputs.image_name }}:${{ steps.docker_vars.outputs.tag_date }}-${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.sha_short }}
```
