### ISSUE TITLE
Labels values are messed up in the latest version (0.10.1 and 0.10.2)

### ISSUE THREAD

**Issue by khhipparagi** [docker/buildx#1590]
Hi,

The `labels` values are messed up in the latest version.

docker-compose-labels.yml

```
version: '3.4'

x-labels: &labelsInfo
  # reference from https://github.com/opencontainers/image-spec/blob/main/annotations.md
  org.opencontainers.image.vendor: "My Company"
  org.opencontainers.image.authors: "khipparagi"
  org.opencontainers.image.source: "https://github.com/"
  org.opencontainers.image.revision: "${GITHUB_SHA:-NA}"
  org.opencontainers.image.build.created: "${BUILD_TIMESTAMP:-NA}"

x-args: &buildArgs
  DOTNET_SDK_DOCKER_TAG: "${DOTNET_SDK_DOCKER_TAG:-6.0}"
  ASPNET_RUNTIME_DOCKER_TAG: "${ASPNET_RUNTIME_DOCKER_TAG:-6.0.11-alpine3.16}"

services:
  sample1:
    image: sample1:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile

      args:
        <<: *buildArgs
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-}sample:latest

      labels:
        <<: *labelsInfo
        org.opencontainers.image.description: "a demo sample app"

  sample2:
    image: sample2:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile

      args:
        <<: *buildArgs
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-}sample2:latest

      labels:
        <<: *labelsInfo
        org.opencontainers.image.description: "a demo sample app2"


```

Here are the test results:

```
$ docker buildx version
github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
$ docker buildx bake -f docker-compose-labels.yml --print
[+] Building 0.0s (0/0)
{
  "group": {
    "default": {
      "targets": [
        "sample2",
        "sample1"
      ]
    }
  },
  "target": {
    "sample1": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "ASPNET_RUNTIME_DOCKER_TAG": "6.0.11-alpine3.16",
        "DOTNET_SDK_DOCKER_TAG": "6.0"
      },
      "labels": {
        "org.opencontainers.image.authors": "khhipparagi",
        "org.opencontainers.image.build.created": "NA",
        "org.opencontainers.image.description": "a demo sample app",
        "org.opencontainers.image.revision": "NA",
        "org.opencontainers.image.source": "https://github.com/",
        "org.opencontainers.image.vendor": "My Company"
      },
      "tags": [
        "sample:latest"
      ]
    },
    "sample2": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "ASPNET_RUNTIME_DOCKER_TAG": "6.0.11-alpine3.16",
        "DOTNET_SDK_DOCKER_TAG": "6.0"
      },
      "labels": {
        "org.opencontainers.image.authors": "khhipparagi",
        "org.opencontainers.image.build.created": "NA",
        "org.opencontainers.image.description": "a demo sample app2",
        "org.opencontainers.image.revision": "NA",
        "org.opencontainers.image.source": "https://github.com/",
        "org.opencontainers.image.vendor": "My Company"
      },
      "tags": [
        "sample2:latest"
      ]
    }
  }
}

$ docker buildx version
github.com/docker/buildx v0.10.1 481796f84fe2f27d0ea19e368a7b9e0ac6ea636d
philips@INGBTCPIC6VL342:~/Kareppa$ docker buildx bake -f docker-compose-labels.yml --print
[+] Building 0.0s (0/0)
{
  "group": {
    "default": {
      "targets": [
        "sample2",
        "sample1"
      ]
    }
  },
  "target": {
    "sample1": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "ASPNET_RUNTIME_DOCKER_TAG": "6.0.11-alpine3.16",
        "DOTNET_SDK_DOCKER_TAG": "6.0"
      },
      "labels": {
        "org.opencontainers.image.authors": "a demo sample app",
        "org.opencontainers.image.build.created": "a demo sample app",
        "org.opencontainers.image.description": "a demo sample app",
        "org.opencontainers.image.revision": "a demo sample app",
        "org.opencontainers.image.source": "a demo sample app",
        "org.opencontainers.image.vendor": "a demo sample app"
      },
      "tags": [
        "sample:latest"
      ]
    },
    "sample2": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "ASPNET_RUNTIME_DOCKER_TAG": "6.0.11-alpine3.16",
        "DOTNET_SDK_DOCKER_TAG": "6.0"
      },
      "labels": {
        "org.opencontainers.image.authors": "NA",
        "org.opencontainers.image.build.created": "NA",
        "org.opencontainers.image.description": "NA",
        "org.opencontainers.image.revision": "NA",
        "org.opencontainers.image.source": "NA",
        "org.opencontainers.image.vendor": "NA"
      },
      "tags": [
        "sample2:latest"
      ]
    }
  }
}

```
