### ISSUE TITLE
It's not possible to use network in build stage,network mode "...." not supported by buildkit

### ISSUE THREAD

**Issue by uchar** [docker/buildx#2085]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have 2 docker-compose files for creating networks and an API :
```
version: '3.8'
networks:
  my_network:
    external: false
    name: my_network
```

```
version: '3.8'
networks:
  my_network:
    external: true
services:
  api:
     container_name: "api"
     networks:
       - my_network
    .....
```
Now in the third one I want to use API in build stage, so I write this one : 
```
version: '3.8'
networks:
  my_network:
    external: true
services:
  frontend:
     networks:
       - my_network
     external_links:
       - api
     build:
       network: my_network
      .....
```
with this docker file 

```
FROM node:18-alpine3.16 AS builder
RUN while ! nc -zv $GRAPHQL_URL; do sleep 5; done && sleep 10
```
but it fails with this error : 
`network mode "my_network" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create` 

this is probably related to https://github.com/docker/buildx/issues/175 from a couple of years ago, which has some weird solutions, but as far as I tested none of them worked

### Expected behavior

This should works fine

### Actual behaviour

faild with error `network mode "my_network" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create`

### Buildx version

github.com/docker/buildx v0.11.2 9872040

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-26-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.92GiB
 Name: srv9045604020
 ID: 181c901d-dda3-48a1-952e-c89810ae32ca
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
default default         running v0.11.6+616c3f613b54 linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

It's in description
