### ISSUE TITLE
Add Concurrency Control to Matrix Builds

### ISSUE THREAD

**Issue by dennisoehme** [docker/buildx#2581]
### Description

Introduce an option to limit the number of concurrent builds when using Docker Buildx (Bake) to manage matrix builds. This feature would help users control system load and optimize resource utilization during complex build processes.

## Description

Currently, Docker Buildx Bake allows users to define and run matrix builds, which can potentially execute a large number of targets in parallel. However, there is no built-in option to limit the concurrency of these builds. This can lead to excessive system load, especially on resource-constrained environments.

## Proposed Solution

1) Add a new option to the docker buildx bake command that allows users to specify the maximum number of concurrent build jobs. This option, tentatively named --max-parallel, would control the number of builds executed simultaneously.
2) Add a concurrency field to the target definitions in the docker-bake.hcl file, enabling users to specify the maximum number of concurrent builds for each target group or individual target.

```hcl
target "build" {
  inherits = ["_common"]
  name = "${PROJECT}-build"
  matrix = {
    "PROJECT" = [...]
  }
  concurrency = 2
}
```

What do you think, guys? :-)

**Comment by crazy-max** [comment]
Looks good but don't think this should be specific to `matrix` but overall invoked build targets so should be only set as flag or env imo.

**Comment by vishalnandagopal** [comment]
> External Download Limits: When Docker builds need to receive downloads from a third-party source that limits the number of parallel requests, controlling concurrency becomes essential. Without such control, exceeding the allowed number of parallel requests can result in build failures or throttling from the third-party service. By specifying concurrency limits in the build configuration, users can ensure compliance with these external constraints while optimizing build efficiency.

This is an important use case.. If I have 5-6 JS projects, they are all built concurrently with docker bake. This leads to me being rate limited by NPM/yarn server or else just the network timing out.

All targets are built successfully independently, and having 2-3 targets in `default` group is fine. But when i try to include more, it causes network errors

**Comment by crazy-max** [comment]
> Please add this. We are building over 150 images in one docker-bake.hcl file, and when they're all trying to push layers at the end, the entire thing freezes up.
> 
> Please add the option to limit the builder to only work on X amount of things at a time.

@MalteMagnussen As you're building with the `docker-container` driver you can already limit parallelism  in the builder directly: https://docs.docker.com/build/buildkit/configure/#max-parallelism

Create this TOML file:

```toml
[worker.oci]
  max-parallelism = 4
```

```
$ docker buildx create --use \
  --name mybuilder \
  --driver docker-container \
  --buildkitd-config /tmp/buildkitd.toml
```

You can place it in default locations: https://docs.docker.com/reference/cli/docker/buildx/create/#buildkitd-config

Like `~/.docker/buildx/buildkitd.default.toml` so you don't need to pass it everytime you invoke `buildx create`:

```
$ docker buildx create --use \
  --name mybuilder \
  --driver docker-container
```

I will look if we can have a buildkitd flag to set max parallelism so you don't need to create a config file just for this.

**Comment by MalteMagnussen** [comment]
@crazy-max Thanks!! I really appreciate it. I'll add that to our docs.

**Comment by MalteMagnussen** [comment]
@crazy-max Ended up adding this to our repo.

`buildkitd.toml`

```toml
# The TOML file used to configure the buildkitd daemon settings 
# has a short list of global settings followed by a series of sections for specific areas of daemon configuration.
#
# The file path is /etc/buildkit/buildkitd.toml for rootful mode, 
# ~/.config/buildkit/buildkitd.toml for rootless mode.
#
# https://docs.docker.com/build/buildkit/toml-configuration/

[worker.oci]
  # When too many workers are running, it can actually slow down the build process, or freeze the machine.
  # So many images can be open at once, that your machine runs out of memory, and starts using the swap file.
  max-parallelism = 6
```

`Makefile`

```make
bake-builder-local:
	@echo "Creating local builder..."
	docker buildx create --use --driver docker-container --name docker-container --buildkitd-config ./buildkitd.toml
	docker buildx inspect
```
