### ISSUE TITLE
Permissions errors on kubernetes build driver (user:anonymous)

### ISSUE THREAD

**Issue by giulioprovasi** [docker/buildx#267]
When trying to build an image with `kubernetes` driver I get the following error

```
User "system:anonymous" cannot create resource "deployments" in API group "apps" in the namespace "myNamespace"
```

Docker version
```
➜  ~ docker version
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14
 Git commit:        afacb8b7f0
 Built:             Mon Mar 16 22:23:09 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14
  Git commit:       afacb8b7f0
  Built:            Mon Mar 16 22:22:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.3.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Buildx version
```
➜  ~ docker buildx version
github.com/docker/buildx v0.3.1-59-g09339bf 09339bf500af9b0a8e6d5c2d325f59c0fa1a123a
```

Create builder
```
KUBECONFIG=$HOME/.kube/config \
    docker buildx create \
        --name mybuilder \
        --driver kubernetes \
        --driver-opt image=moby/buildkit:master \
        --driver-opt replicas=3 \
        --driver-opt loadbalance=sticky \
        --driver-opt rootless=false \
        --driver-opt namespace=myNamespace \
        --use
```

Run build
```
docker buildx build \
    --builder mybuilder \
    --ssh gitlab=$HOME/.ssh/gitlab_rsa \
    --target build-cli \
    --tag myregistry:443/test/cli:buildkit \
    --output "type=image,push=false"
    --output "type=docker" \
    -f ./Dockerfile \
    .
```

My kube config file :
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://xxx
  name: acme.com
contexts:
- context:
    cluster: acme.com
    namespace: myNamespace
    user: my-actual-user-acme.com
  name: my-actual-user-acme.com
current-context: my-actual-user-acme.com
kind: Config
preferences: {}
users:
- name: my-actual-user-acme.com
  user:
    token: xxx
```

Note that the cluster is handled by production team and I am not a cluster admin, this may cause the issue ?
