### ISSUE TITLE
`docker buildx bake` not loading private git contexts: "could not read Username for 'https://github.com': terminal prompts disabled"

### ISSUE THREAD

**Issue by swanysimon** [docker/buildx#2694]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I want to share service image base structures between private GitHub projects, so I have a Dockerfile in `private/repository.git` that specifies a `service-builder` target that accepts a Python image tag for consumers to use. Locally this works great, but in CI I cannot build because the services cannot authenticate to GitHub from docker.

### Expected behaviour

I can bake with contexts from private repositories by using a valid GitHub token.

### Actual behaviour

I cannot bake from private repository contexts.

### Buildx version

github.com/docker/buildx v0.16.2 99dea6dacacc3d604788953088560b9880550570

### Docker info

```text
/usr/bin/docker version
  Client: Docker Engine - Community
   Version:           26.1.3
   API version:       1.45
   Go version:        go1.21.10
   Git commit:        b72abbb
   Built:             Thu May 16 08:33:29 2024
   OS/Arch:           linux/amd64
   Context:           default
  
  Server: Docker Engine - Community
   Engine:
    Version:          26.1.3
    API version:      1.45 (minimum version 1.24)
    Go version:       go1.21.10
    Git commit:       8e96db1
    Built:            Thu May 16 08:33:29 2024
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.7.21
    GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
   runc:
    Version:          1.1.13
    GitCommit:        v1.1.13-0-g58aa920
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/bin/docker info
  Client: Docker Engine - Community
   Version:    26.1.3
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.16.2
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.27.1
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 15
   Server Version: 26.1.3
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
   runc version: v1.1.13-0-g58aa920
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 6.5.0-1025-azure
   Operating System: Ubuntu 22.04.4 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 7.744GiB
   Name: fv-az713-494
   ID: 30759ade-e034-4128-bb61-2ac11859f059
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
```
```


### Builders list

```text
(This is from the builder info section from the GitHub action, if you need something else I'm happy to grab it)


  {
    "nodes": [
      {
        "name": "default",
        "endpoint": "default",
        "status": "running",
        "buildkit": "v0.13.2",
        "platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386",
        "features": {
          "Automatically load images to the Docker Engine image store": true,
          "Cache export": true,
          "Docker exporter": true,
          "Multi-platform build": true,
          "OCI exporter": true
        },
        "labels": {
          "org.mobyproject.buildkit.worker.moby.host-gateway-ip": "172.17.0.1"
        }
      }
    ],
    "name": "default",
    "driver": "docker"
  }
```

### Configuration

```hcl
variable "GITHUB_BASE" {
  default = "git@github.com:" 
}

variable "PRIVATE_CONTEXT" {
  default = "private/context.git#v0.1.2"
}

group "default" {
  targets = ["service"]
}

target "service" {
  tags = ["service:latest"]
  contexts = {
    service-builder = "target:service-builder"
  }
}

target "service-builder" {
  context = "${GITHUB_BASE}${PRIVATE_CONTEXT}"
  target = "poetry-service-builder-base"
  args = {
    PYTHON_IMAGE_TAG = "3.12"
  }
}
```

And then in GitHub actions:

```yaml
...
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify token can access 'private/context'
        uses: actions/checkout@v3
        with:
          repository: private/context
          ref: refs/heads/main
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          persist-credentials: false
          path: ./.github/deergod/no

      # I have also tried using `run` and setting [BUILDX_BAKE_GIT_AUTH_TOKEN](https://docs.docker.com/build/building/variables/#buildx_bake_git_auth_token)
      - name: Build container images
        uses: docker/bake-action@v5
        with:
          no-cache: true
          pull: true
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        env:
          GITHUB_BASE: https://github.com/
```

### Build logs

```text
/usr/bin/docker buildx bake --metadata-file /home/runner/work/_temp/docker-actions-toolkit-q6nLMp/bake-metadata-5c86828817.json --no-cache --pull
#0 building with "default" instance using docker driver

#1 [internal] load local bake definitions
#1 reading docker-compose.yml 402B / 402B done
#1 reading docker-bake.hcl 1.14kB / 1.14kB done
#1 DONE 0.0s

------
 > [service-builder internal] load git source https://github.com/private/context.git#v0.1.2:
0.029 Initialized empty Git repository in /var/lib/docker/overlay2/22z3pws8u31wdepeigefwz9p2/diff/
0.101 fatal: could not read Username for 'https://github.com': terminal prompts disabled
------
ERROR: failed to solve: failed to read dockerfile: failed to load cache key: failed to fetch remote https://github.com/private/context.git: git error: exit status 128
stderr:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

Build references
Check build summary support
Error: buildx bake failed with: fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
```


### Additional info

I've scrubbed all actually private information but it's not hard to get you things that might be missing.

**Comment by dvdksn** [comment]
`BUILDX_BAKE_GIT_AUTH_TOKEN` is for loading remote bake files in private repositories, but you're using a local definition. For fetching private git contexts, are you using the `GIT_AUTH_TOKEN` secret in your build? https://docs.docker.com/build/building/secrets/#git-authentication-for-remote-contexts

**Comment by swanysimon** [comment]
The documentation read to me as if `BUILDX_BAKE_GIT_AUTH_TOKEN` superseded `GIT_AUTH_TOKEN` but on reread I see that's not true.

I tried adding `GIT_AUTH_TOKEN` instead, but still have the same error:

```yaml
      - name: Build container images
        env:
          GIT_AUTH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_BASE: https://github.com/
        run: docker buildx bake --pull --no-cache
```
