### ISSUE TITLE
Error: buildx failed with: ERROR: failed to receive status: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"

### ISSUE THREAD

**Issue by PanDeOps** [docker/buildx#2789]
**Contributing guidelines**

- [ ] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

**I've found a bug and checked that ...**

- [ ] ... the documentation does not mention anything about my problem

- [ ] ... there are no open or closed issues that are related to my problem

**Description**

Greetings

On own ubuntu server via github CI when multibuilding containers (4 pcs) at the end of the docker/build-push-action@v6 module one of the processes crashes with an error on completion, this happens quite often when first running with git action..:
```bash
...
#12 pushing layers
#12 ...

#13 [auth] ***/backend:pull,push token for registry-1.docker.io
#13 DONE 0.0s

#12 exporting to image
#12 ...

#14 [auth] ***/backend:pull,push ***/app:pull token for registry-1.docker.io
#14 DONE 0.0s

#12 exporting to image
ERROR: failed to receive status: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"

Check build summary support
  Build summary requires a build reference
Error: buildx failed with: ERROR: failed to receive status: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"
```
From the log, I noticed that the push produced an entry from a different container (***/app:pull)

After restarting the crashed container is built correctly.

This is the part of the yml that is used in the build:
```yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
          logout: false

      - name: Build and push Docker image for ${{ inputs.serviceName }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./${{ inputs.workingDirectory }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.username }}/${{ inputs.imageName }}:${{ vars.LABEL }}
```

Docker info:
```bash
docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-122-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 61.31GiB
 Name: server
 ID: 6c716f54-62b4-469e-9f99-aa2aabec961e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Can anyone explain what the error is (or how it appears) and how to fix it?

**Comment by crazy-max** [comment]
This looks similar to https://github.com/docker/build-push-action/issues/1257

Do you have a link to your repo or is it private?

**Comment by PanDeOps** [comment]
it's private repo

**Comment by erikburt** [comment]
We've seen a similar error in our public repo: https://github.com/smartcontractkit/chainlink/actions/runs/11808083477/job/32896022220

Only seen it for ARM64 builds (on Github-hosted ARM64 runners), I've also seen a few other errors.

**Comment by erikburt** [comment]
Here's an EOF error with Buildkit debug logs, although it appears different than the error that was originally posted about.

 https://github.com/smartcontractkit/chainlink/actions/runs/11863864029/job/33066447611?pr=15272#step:7:93

```
level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Internal desc = rpc error: code = Internal desc = unexpected EOF" ...
Internal: rpc error: code = Internal desc = unexpected EOF
```

**Comment by crazy-max** [comment]
This is similar to https://github.com/docker/build-push-action/issues/1257, https://github.com/docker/build-push-action/issues/1263 and has been fixed in https://github.com/moby/buildkit/pull/5530.

You can either downgrade buildkit in your workflow:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.16.0
```

Or use a version from master with the fix in the meantime:

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:nightly@sha256:b26268202a6d69bed47856db1a625b3fde1c3bfb0bf38c0873496d6b5b0df6ca
```
