### ISSUE TITLE
Feature request: Allow storing builder configurations in a file

### ISSUE THREAD

**Issue by lumattr** [docker/buildx#2799]
### Description

I would like to use the multiplatform building in my CI but ideally i would like to predefine a config file for consistency rather that having to run `docker buildx create` and appending for platform types. It would be good if i could do something like `docker buildx create --from builders.yaml` and then jump straight into building.

i.e.

```yaml
# builders.yaml
kube:
  arm64:
    driver: kubernetes
    driver-opt: 
      namepace: buildkit
      nodeselector: "kubernetes.io/arch=arm64"
    platform:
      - linux/arm64
  amd64:
    driver: kubernetes
    driver-opt: 
      namepace: buildkit
      nodeselector: "kubernetes.io/arch=amd64"
    platform:
      - linux/amd64
```
