### ISSUE TITLE
docker buildx bake should apply env variable from .env

### ISSUE THREAD

**Issue by vinverdy** [docker/buildx#282]
docker buildx should read .env file like compose. Kudos

docker-compose.yml
```
version: '3.6'

services:
    ssr:
        build:
            context: .
            target: ssr
            args:
                COMMIT_SHA: ${COMMIT_SHA}
```
.env
```
COMMIT_SHA=a06baf1a
```

docker-compose config
```
services:
  ssr:
    build:
      args:
        COMMIT_SHA: a06baf1a
      context: 
      target: ssr
version: '3.6'
```

docker buildx bake --print
```
{
   "target": {
      "ssr": {
         "context": ".",
         "dockerfile": "Dockerfile",
         "args": {
            "COMMIT_SHA": ""
         },
         "target": "ssr"
      }
   }
}
```

**Comment by tonistiigi** [comment]
@tiborvass @FernandoMiguel wdyt? I remember discussing this case some time ago with at least one of you.

**Comment by FernandoMiguel** [comment]
I remember opening this 
https://github.com/docker/buildx/issues/111

but yeah, there is expectation for those values to be read...

**Comment by ktns** [comment]
If you think it's a burden to have an docker-compose.yml parser in buildx for this, what about using `docker-compose config` command for expanding environment variables? It outputs the content with all environment variables substituted.

Maybe it should not be a default behavior, but I'll be happy if there is such an option.

**Comment by crazy-max** [comment]
If it's the right direction, #489 can be tested if you want: https://github.com/docker/buildx/suites/1696585811/artifacts/31897347

**Comment by aeaton-overleaf** [comment]
I'm working around this with `env $(cat .env | grep -v "#" | xargs) docker buildx …` but it would be useful to be able to specify `--env-file=.env` as an option even if it's not on by default.

**Comment by crazy-max** [comment]
Fixed by https://github.com/docker/buildx/pull/541

**Comment by zachary-povey** [comment]
Hi 👋 - I think this should be re-opened. 

#541 allows specifying this kind of file for HCL configurations but doesn't give any options for people still using `docker-compose`. The `.env` file is still not read automatically and passing it through using `-f` also does not work nor does using the default `docker-bake.override.hcl` file.

@tonistiigi mentions this in the issue:

> The HCL attributes are not 100% compatible with env file format so I think for compose support we still should have a fallback, and maybe still automatically load it if you parse compose. Possibly we can just use the new compose library that does that automatically on parsing compose. For everything else, you can use HCL/JSON attributes.

**Comment by crazy-max** [comment]
@trinitronx This should be fixed by https://github.com/docker/buildx/pull/905 (not released yet but you can [build from source](https://github.com/docker/buildx#building))

**Comment by cdupont** [comment]
I tried buildx v0.8.0 but it doesn't seem to be fixed.

docker-compose.yml:
```
version: "3.9"

services:
  foo:
    image: foo:$TAG
```

.env:
```
TAG=bar
```

```
$ docker buildx bake
[+] Building 0.0s (0/0)                                                                                                                        
WARNING: The "TAG" variable is not set. Defaulting to a blank string.
```
