### ISSUE TITLE
Action v6 using --cache-from isn't compatible with latest docker buildx 0.20.0

### ISSUE THREAD

**Issue by farvour** [docker/buildx#2942]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/build-push-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

When trying to use this Action `@v6` with the latest Docker Buildx 0.20.0, the `--cache-from` directive causes an error.

We are using a CSV list of values for `cache-from` which appear to get squashed together on a single `--cache-from` CSV. Whereas, the tag values are separated into separate `--tag`.

### Expected behaviour

Buildx action builds with arguments properly.

### Actual behaviour

```
Error: buildx failed with: ERROR: invalid value <REDACTED>.dkr.ecr.us-gov-west-1.amazonaws.com/app:git-000
```

### YAML workflow

```yaml
- name: Build, tag and push image to ECR - stage1
        uses: docker/build-push-action@v6
        with:
          context: "${{ steps.app-dockerfile-selector.outputs.context }}"
          file: "${{ steps.app-dockerfile-selector.outputs.dockerfile }}"
          target: stage1
          push: true
          tags: "${{ steps.docker-set-build-tags.outputs.tags }}" # < CSV list
          platforms: "${{ steps.docker-set-build-vals.outputs.platform }}"
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BUILD_GIT_SHA=${{ needs.prebuild.outputs.head-ref-short-sha }}
          cache-from: "${{ steps.docker-set-build-tags-cache-from.outputs.tags }}" # < CSV list
```

### BuildKit logs

```text

```

### Additional info

Is it related to this? https://github.com/docker/buildx/pull/2814
