### ISSUE TITLE
Problem with layers after upgrade to buildx v0.20.x

### ISSUE THREAD

**Issue by lukidzi** [docker/buildx#2952]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

We have a flow that builds mutliplatform images with multiple tags:

```yaml
  build-image:
    name: Build Image
    needs: [get-version]
    runs-on: ubuntu-latest
    steps:
...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          install: true
          version: v0.20.1
      - name: Build container
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: Dockerfile
          platforms: "linux/amd64,linux/arm64"
          push: false
          outputs: "type=oci,tar=false,dest=docker-archive"
          tags: |
            repo/test:v1,repo/test:latest
          build-args: |
            BUILD_DATETIME=${{ github.event.repository.updated_at }}
```

```sh
/usr/bin/docker buildx build --file Dockerfile --output type=oci,tar=false,dest=docker-archive --platform linux/amd64,linux/arm64 --tag repo/test:latest --tag repo/test:v1.
```

 

### Expected behaviour

Tools were working

### Actual behaviour

We were using 2 tools: `crane` and `skopeo`, one to push registry, another to create a docker archive for some scanning tool. Since upgrade to v0.20.x both tools are broken:

Crane
```sh
crane push docker-archive repo/test:v1
  
Error: layout contains 2 entries, consider --index
```

skeope
```
skopeo copy --override-arch arm64 oci:docker-archive docker-archive:docker-archive-arm64.tar
skopeo copy --override-arch amd64 oci:docker-archive docker-archive:docker-archive-amd64.tar


....
level=fatal msg="initializing source oci:docker-archive:: more than one image in oci, choose an image"
```

### Buildx version

github.com/docker/buildx v0.20.1 245093b99ab74aa2c729a496759afca0704d6470

### Docker info

```text
/usr/bin/docker version
  Client: Docker Engine - Community
   Version:           26.1.3
   API version:       1.45
   Go version:        go1.21.10
   Git commit:        b72abbb
   Built:             Thu May 16 08:33:35 2024
   OS/Arch:           linux/amd64
   Context:           default
  
  Server: Docker Engine - Community
   Engine:
    Version:          26.1.3
    API version:      1.45 (minimum version 1.24)
    Go version:       go1.21.10
    Git commit:       8e96db1
    Built:            Thu May 16 08:33:35 2024
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.7.25
    GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
   runc:
    Version:          1.2.4
    GitCommit:        v1.2.4-0-g6c52b3f
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/bin/docker info
  Client: Docker Engine - Community
   Version:    26.1.3
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.20.1
      Path:     /home/runner/.docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.27.1
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  Server:
   Containers: 1
    Running: 1
    Paused: 0
    Stopped: 0
   Images: 1
   Server Version: 26.1.3
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: systemd
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
   runc version: v1.2.4-0-g6c52b3f
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 6.8.0-1020-azure
   Operating System: Ubuntu 24.04.1 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 7.753GiB
   Name: fv-az1396-8
   ID: bf2dc864-ec07-402e-b2a5-3513720aaacc
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
```

### Builders list

```text
{
    "nodes": [
      {
        "name": "builder-054c3b73-c604-4ad5-914d-0ddd6907a2140",
        "endpoint": "unix:///var/run/docker.sock",
        "status": "running",
        "buildkitd-flags": "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host",
        "buildkit": "v0.18.2",
        "platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386",
        "features": {
          "Automatically load images to the Docker Engine image store": true,
          "Cache export": true,
          "Docker exporter": true,
          "Multi-platform build": true,
          "OCI exporter": true
        },
        "labels": {
          "org.mobyproject.buildkit.worker.executor": "oci",
          "org.mobyproject.buildkit.worker.hostname": "c657d8ba495a",
          "org.mobyproject.buildkit.worker.network": "host",
          "org.mobyproject.buildkit.worker.oci.process-mode": "sandbox",
          "org.mobyproject.buildkit.worker.selinux.enabled": "false",
          "org.mobyproject.buildkit.worker.snapshotter": "overlayfs"
        },
        "gcPolicy": [
          {
            "all": false,
            "filter": [
              "type==source.local",
              "type==exec.cachemount",
              "type==source.git.checkout"
            ],
            "keepDuration": "48h0m0s"
          },
          {
            "all": false,
            "keepDuration": "1440h0m0s"
          },
          {
            "all": false
          },
          {
            "all": true
          }
        ]
      }
    ],
    "name": "builder-054c3b73-c604-4ad5-914d-0ddd6907a214",
    "driver": "docker-container",
    "lastActivity": "2025-01-24T15:16:50.000Z"
  }
```

### Configuration

```dockerfile
FROM alpine:latest
CMD ["echo", "Hello, World!"]
```

### Build logs

```text

```
