### ISSUE TITLE
support multi-arch build with driver kubenetes.

### ISSUE THREAD

**Issue by morlay** [docker/buildx#342]
```
docker buildx create --use --name buildx --node buildx-arm64 --platform=linux/arm64 --driver=kubernetes --driver-opt="image=moby/buildkit:master,replicas=2,namespace=gitlab"
	
docker buildx create --append --name buildx --node buildx-amd64 --platform=linux/amd64 --driver=kubernetes --driver-opt="image=moby/buildkit:master,replicas=2,namespace=gitlab"
```

`--append` now works when `--driver=kubernetes`.

When just with one cli in my multi-arch k8s cluster (with `affinities` could make pod in each arch host).
```
docker buildx create --use --name buildx --node buildx--platform=linux/amd64, linux/arm64 --driver=kubernetes --driver-opt="image=moby/buildkit:master,replicas=2,namespace=gitlab"
```

platform of node is wrong, and build jobs are dispatched to wrong pod.

```
Name:   buildx
Driver: kubernetes

Nodes:
Name:      buildx-647b4d4b6f-5xf2m
Endpoint:  
Status:    running
Platforms: linux/arm64

Name:      buildx-647b4d4b6f-gt7xk
Endpoint:  
Status:    running
Platforms: linux/arm64
```

**Comment by tonistiigi** [comment]
@AkihiroSuda

**Comment by AkihiroSuda** [comment]
A single kube cluster with mixed arch isn't currently supported. Help wanted.

**Comment by morlay** [comment]
@AkihiroSuda  
is that possible to make `--append` works for `kubeneters` driver, like 'docker-container' did?

**Comment by rolandjitsu** [comment]
@AkihiroSuda does this mean that if we want to use buildx with the kubernetes driver to build for different architectures than the pod's architecture, it's not possible?

**Comment by AkihiroSuda** [comment]
binfmt may work probably

**Comment by rolandjitsu** [comment]
> binfmt may work probably

Hmm ... and how would I run that on the pod?

Say I've created this builder:
```bash
docker buildx create --name my-kube --driver kubernetes --use
```

Now I bootstrap it:
```bash
docker buildx inspect --bootstrap
```

And now I try to bake something:
```bash
docker buildx bake -f ./docker-bake.hcl
```

But this fails because the dockerfile is using `RUN` and `FROM arm32v7/debian:stretch AS builder` which is not supported on the host.

**Comment by AkihiroSuda** [comment]
`docker run --privileged --rm tonistiigi/binfmt --install all` on each of the nodes. (Can be Kubernetes Daemonset)

**Comment by rolandjitsu** [comment]
> `docker run --privileged --rm tonistiigi/binfmt --install all` on each of the nodes. (Can be Kubernetes Daemonset)

Thanks @AkihiroSuda. Using a DaemonSet seems to do the trick!

**Comment by morlay** [comment]
@AkihiroSuda 

Daemonset could not only run once

it that possible to provider `--wait` to keep alive ? 
and auto uninstall when pod killed?

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: binfmt
spec:
  selector:
    matchLabels:
      app: binfmt
  template:
    metadata:
      labels:
        app: binfmt
    spec:
      containers:
        - name: binfmt
          image: tonistiigi/binfmt
          args:
            - --wait
            - --install
            - all
          securityContext:
            privileged: true
          imagePullPolicy: Always
```

**Comment by rolandjitsu** [comment]
> @AkihiroSuda
> 
> Daemonset could not only run once
> 
> it that possible to provider `--wait` to keep alive ?
> and auto uninstall when pod killed?
> 
> then could use the DaemonSet
> 
> ```yaml
> kind: DaemonSet
> apiVersion: apps/v1
> metadata:
>   name: binfmt
> spec:
>   selector:
>     matchLabels:
>       app: binfmt
>   template:
>     metadata:
>       labels:
>         app: binfmt
>     spec:
>       containers:
>         - name: binfmt
>           image: tonistiigi/binfmt
>           args:
>             - --wait
>             - --install
>             - all
>           securityContext:
>             privileged: true
>           imagePullPolicy: Always
> ```

I use this:
```yaml
# Run binfmt setup on any new node
# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset
# https://github.com/docker/buildx/issues/342#issuecomment-680715762
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: binfmt
  # namespace: kube-system
  labels:
    app: binfmt-setup
spec:
  selector:
    matchLabels:
      name: binfmt
  # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
  template:
    metadata:
      labels:
        name: binfmt
    spec:
      tolerations:
        # Have the daemonset runnable on master nodes
        # NOTE: Remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
        - name: binfmt
          image: tonistiigi/binfmt
          # command: []
          args: ["--install", "all"]
          # Run the container with the privileged flag
          # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
```
