### ISSUE TITLE
Can't export images to local registry

### ISSUE THREAD

**Issue by jimwelagu** [docker/buildx#347]
I'm getting an error when buildx tries to export images to my local registry.

I use the following command to create the builder:
```
docker buildx create --use --name builder --driver-opt network=host
```

However after doing a build, I get the following errors. I try both `localhost:5000` and `127.0.0.1:5000`

Output when pushing image to localhost:5000:
```
#34 ERROR: failed to do request: Head http://localhost:5000/v2/listener/blobs/........./http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Output when pushing image to 127.0.0.1:5000:
```
#34 ERROR: failed to do request: Head http://127.0.0.1:5000/v2/listener/blobs/......./http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

I noticed that it is not using https which might be the cause of the error?
Is there something under the hood that requires localhost and 127.0.0.1 to use http instead of https?

**Comment by tonistiigi** [comment]
Yes, containerd sets localhost to default to https://github.com/containerd/containerd/blob/master/remotes/docker/resolver.go#L185 . I believe you can override it though if you add a custom config for the local registry with `HTTP = false`

**Comment by spkane** [comment]
@tonistiigi Where exactly does this get set?

I have the same issue, but even after a bunch of googling I am not sure where this should be configured, so that `buildx --push` does the right thing.

**Comment by spkane** [comment]
A little more research and I am guessing that it is something like setting the following in `/etc/containerd/config.toml`, followed by a restart of contained.

* But this is not working, so I am still playing around with it a bit.

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."127.0.0.1:5000"]
      endpoint = ["https://127.0.0.1:5000"]
      HTTP = false
```
