### ISSUE TITLE
Unable build docker-compose file with advanced network configuration

### ISSUE THREAD

**Issue by mik-laj** [docker/buildx#612]
Hello,

I wanted to build images with `docker buildx bake` command, but my file has the following network configuration.

```
networks:
  example.com:
    name: example.com
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          ip_range: 10.5.0.0/24
          gateway: 10.5.0.254

```
but I got the following error:
```
error: networks.example.com.ipam.config.0 Additional property gateway is not allowed
Error: Process completed with exit code 1.
```

Docker-Buildx 0.5.1
Full spec: https://github.com/actions/virtual-environments/blob/ubuntu20/20210510.0/images/linux/Ubuntu2004-README.md
