### ISSUE TITLE
failed to docker buildx build github actions

### ISSUE THREAD

**Issue by yuzujoe** [docker/buildx#688]
## What's troubling

I'm getting the following error when trying to run a multi-arch build with docker buildx, but I'm not sure what to look for

```shell
[linux/arm64 2/7] RUN apk update && apk upgrade && apk add --update --no-cache bash git openssh python3 make g++:
#6 0.504 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/aarch64/APKINDEX.tar.gz
#6 3.409 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/aarch64/APKINDEX.tar.gz
#6 7.583 v3.13.5-246-g50ebda534a [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
#6 7.583 v3.13.5-244-g25c727c5f3 [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
#6 7.583 OK: 13739 distinct packages available
#6 15.01 Upgrading critical system libraries and apk-tools:
#6 15.02 (1/1) Upgrading apk-tools (2.12.4-r0 -> 2.12.5-r0)
#6 16.62 Executing busybox-1.32.1-r5.trigger
#6 18.80 Continuing the upgrade transaction with new apk-tools:
------
Dockerfile:5
--------------------
   3 |     ENV LANG C.UTF-8
   4 |     
   5 | >>> RUN apk update && apk upgrade && apk add --update --no-cache bash git openssh python3 make g++
   6 |     
   7 |     WORKDIR /app
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c apk update && apk upgrade && apk add --update --no-cache bash git openssh python3 make g++" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.
```

The configuration of the dockerfile looks like this

```dockerfile
FROM node:14.16.0-alpine3.13

ENV LANG C.UTF-8

RUN apk update && apk upgrade && apk add --update --no-cache bash git openssh python3 make g++

WORKDIR /app
```

```yaml
# .github/workflows/test.yaml

name: Test

on:
  pull_request_target:

jobs:
  testing:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: install
        run: npm install

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        id: docker_build
        run: |
          set -eu
          docker buildx build --platform linux/amd64,linux/arm64 \
          -t apdd:${GITHUB_SHA} -f .
```

## platform
AmazonLinux2 (Github Actions Self Hosted Runner)
