### ISSUE TITLE
bake fails when version field is omitted from compose file

### ISSUE THREAD

**Issue by dudicoco** [docker/buildx#719]
When the `version` field is omitted from a compose file (as per the new specification), the `bake` command fails.

Example file:
```yaml
services:
  app:
    image: test:latest
    build: .
```

Output:
```sh
$ docker buildx bake
[+] Building 0.0s (0/0)
error: unsupported Compose file version: 1.0
```
