### ISSUE TITLE
tag and push without building

### ISSUE THREAD

**Issue by dudicoco** [docker/buildx#724]
is it possible to use the `bake` command without building an image, only tagging and pushing an existing image?

use case - when pushing to multiple registries you might want to pass a different environment variable to the `bake` command each time in order to tag and push to a different registry.

Example:

```yaml
services:
  app:
    image: ${DOCKER_REGISTRY:-default}/app
    build:
      context: .
      dockerfile: Dockerfile
```

```sh
docker buildx bake # build the initial image
for registry in registries; do
  export DOCKER_REGISTRY=$registry
  docker buildx bake --push
fi
```

The example above will rebuild the image each time (although from cache).
