### ISSUE TITLE
Pushing an image to GHCR under a new tag fails with 401 Unauthorized

### ISSUE THREAD

**Issue by jauderho** [docker/buildx#734]
This just started happening today for some reason. I have multiple GH actions building docker images that has been working without issue. 

What is odd is that my action is able to login to GH with no issue but is somehow unable to push the built image. 

Here is the error: https://github.com/jauderho/dockerfiles/runs/3353835705?check_suite_focus=true#step:8:7905

GitHub Action: https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/lego.yml

I was able to find a similar issue here (#446) but it did not appear that there was any solution.

**Comment by forana** [comment]
Seeing this as well and actively trying to debug - what it looks like is happening is that the staging with `--push` isn't using authentication. Haven't found a solution yet.

**Comment by crazy-max** [comment]
cc @chrispat

**Comment by forana** [comment]
I can confirm two things:

1. Pushing to GHCR without buildx still works just fine.
2. Nothing about the runner environment, docker, or buildx setup changed between working and failing pushes.

**Comment by Zenexer** [comment]
I've noticed that it's only happening for me when I try to push multiple platforms: https://github.com/docker/build-push-action/issues/437

**Comment by Zenexer** [comment]
Minimal repro: https://github.com/Zenexer/docker-bug-test/actions  Notice that the only difference between the two workflows is that the platforms are split into separate build steps in the working workflow.

**Comment by forana** [comment]
Interesting - though, neither of my failing builds use `--platform` at all.

**Comment by Zenexer** [comment]
@forana, are you able to link to or attach your workflow?

**Comment by forana** [comment]
@Zenexer I can't link directly because they're private repos, but anonymized excerpt:

```yml
 buil:
    name: Build
    runs-on: ubuntu-latest
    env:
      TEST_IMAGE_NAME: ghcr.io/something/something:something
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        run: echo ${{ secrets.SOME_TOKEN }} | docker login ghcr.io -u username --password-stdin
      - name: Build test image
        run: |
          docker buildx build \
            --build-arg SOMETHING=something \
            --tag ${TEST_IMAGE_NAME} \
            --push \
            .
```

It does the build successfully, then hits the 401 while pushing.

**Comment by Zenexer** [comment]
@forana I've made a few attempts to repro it with that, but I haven't had any luck: https://github.com/Zenexer/docker-bug-test/actions?query=branch%3Atest2

**Comment by jauderho** [comment]
Confirming @forana 's comment about images being built with only the push failing. 

From what I can tell from my Actions history, things were working at least 19hrs ago.

**Comment by Zenexer** [comment]
@jauderho, are you attempting to use multiple platforms?  So far, I've only been able to reproduce it when attempting to push multiple platforms.

**Comment by jauderho** [comment]
@Zenexer That is correct. See the action file that I posted up top: https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/lego.yml

**Comment by Zenexer** [comment]
Ah, sorry, didn't realize you were the OP.

As a temporary workaround for workflows with multiple platforms, I've found that duplicating the build/push step so as to create a separate step for each platform works.  That being said, it burns through Actions minutes.

**Comment by chrispat** [comment]
Not sure what is going on here but I have pinged the team.

**Comment by razor-x** [comment]
Just starting see this. Builds that were OK yesterday are now failing without any changes on all project. In case it helps, here is an example I just triggered on one of my public repos: https://github.com/makenew/nodejs-app/runs/3357369781?check_suite_focus=true

**Comment by coolrc136** [comment]
same problem，the build succeeded yesterday and failed today when pushing to ghcr.io。 <https://github.com/LinuxHub-Group/dockerfiles/runs/3359946398?check_suite_focus=true>

**Comment by muzi502** [comment]
same problem +1

**Comment by stefanprodan** [comment]
@chrispat any news on this? In FluxCD org all our release pipelines are broken.

**Comment by crazy-max** [comment]
That's an issue with the GitHub Container Registry. Our [e2e tests on multi registries work fine except for GHCR](https://github.com/docker/build-push-action/actions/runs/1142669998):

![image](https://user-images.githubusercontent.com/1951866/129897884-53b44448-22c9-4e7a-ad46-5a0b8165257e.png)

cc @nilofer

**Comment by forana** [comment]
Got a response on my github support ticket - they've pushed out a fix, and I've confirmed that my builds are now working again.

**Comment by crazy-max** [comment]
Loks solved to me too https://github.com/docker/build-push-action/issues/437#issuecomment-901120161

**Comment by timburgan** [comment]
Yes should be working again now

**Comment by thaJeztah** [comment]
Thanks @timburgan !

**Comment by jauderho** [comment]
@timburgan Are you able to share more on what broke?

**Comment by Zenexer** [comment]
Before I spend a lot of time looking into this, are images now getting tagged with the wrong architectures?  I don't think this is actually resolved, but I don't want to waste time debugging it if the issue I'm running into now is unrelated.

**Comment by Zenexer** [comment]
I've got one repo with an untouched workflow that now has ARM64 artifacts tagged as AMD64.  I suspect the cause is related to the issue described here, as it broke at the same time.  cc @timburgan 

Symptoms include seeing the following error when attempting to use affected images:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

The image will be tagged for the appropriate platform, but the contents will be from a different platform's build.  For example:

```
% docker inspect sha256:a6ce4e8f6e6f49499be39a54f19d893207f6ced9f972040867ab60160a70b942 | grep Architecture
        "Architecture": "amd64",
% docker create sha256:a6ce4e8f6e6f49499be39a54f19d893207f6ced9f972040867ab60160a70b942
66781368c0eb28a17ce136d2b1e1651f0b305f7bd9c908424589d40373730bbe
% docker cp 66781368c0eb28a17ce136d2b1e1651f0b305f7bd9c908424589d40373730bbe:/bin/bash bad-bash
% file bad-bash
bad-bash: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=641209ff5307ca8eb85bd6368cb5f7f2e694897e, for GNU/Linux 3.7.0, stripped
```

It's possible this has something to do with my usage of `cache-from` and `cache-to`, but the same workflow was functioning just fine a few days ago.

Excerpt from the relevant workflow:

``` yaml
      - name: "Build and push"
        uses: "docker/build-push-action@v2"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache-new"  # TODO: Remove this once it's no longer necessary; see "Move cache" step
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"

      # TODO: Remove this once it's no longer necessary
      # https://github.com/docker/build-push-action/issues/252#issuecomment-804898823
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: "Move Docker cache"
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

I'll report shortly whether it's possible to work around the bug by removing cache-from/cache-to and the cache move step.
