### ISSUE TITLE
does gha cache work without using the official action? 

### ISSUE THREAD

**Issue by dudicoco** [docker/buildx#744]
When I try to use the following within GH actions, the cache is not getting exported:
```yaml
    - name: Docker Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker buildx build --load --cache-from=type=gha --cache-to=type=gha,mode=max .
```

However, when using the official action the cache does get exported:
    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

Is gha cache only supported via the official Docker GH action?

**Comment by crazy-max** [comment]
@dudicoco

> Is gha cache only supported via the official Docker GH action?

Yes, see https://github.com/moby/buildkit#github-actions-cache-experimental.

```yaml
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v1
    - name: Docker Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker buildx build --load --cache-from=type=gha --cache-to=type=gha,mode=max .
```
