### ISSUE TITLE
[BUG] failed to solve: rpc error: code = Unknown desc = executor failed running

### ISSUE THREAD

**Issue by juslintek** [docker/buildx#763]
Getting error mentioned in this issue: https://github.com/docker/buildx/issues/101

I am building 3 containers in parallel with same Dockerfile, just different `WORKDIR`

```Dockerfile
FROM php:fpm-alpine

LABEL maintainer="Linas Jusys"

ARG WWWGROUP
ARG WWWUSER

ENV TZ=UTC

RUN set -eux \
    && apk add --no-cache \
        zip \
        unzip \
        git \
        bash \
        shadow \
        imap-dev \
        freetype-dev \
        libmcrypt-dev \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apk add --no-cache --virtual .build-deps \
            $PHPIZE_DEPS \
            libgd \
            postgresql-dev \
            openldap-dev \
            libjpeg-turbo-dev \
            libpng-dev \
            libzip-dev \
            libxml2-dev \
            libx11-dev \
            libwebp-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-configure ldap --with-ldap-sasl \
    && docker-php-ext-install -j$(nproc) gd bcmath pgsql imap zip soap intl ldap pdo_mysql \
    && pecl install memcache xdebug msgpack igbinary redis mcrypt apcu mongodb imagick \
    && docker-php-ext-enable memcache xdebug msgpack igbinary redis mcrypt apcu mongodb imagick \
    && apk del --no-network .build-deps \
    && apk add --no-cache \
        libpng \
        libjpeg \
        libwebp \
        libx11 \
        libc-utils \
        libical \
        libldap \
        libpq \
        libzip \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN (test -z $(getent group $WWWGROUP | cut -d: -f1) || groupmod -g $(($WWWGROUP+1000)) $(getent group $WWWGROUP | cut -d: -f1)) \
    && addgroup -g $WWWGROUP -S tg \
    && adduser -D -h /home/tg -s /bin/bash -u $WWWUSER -G tg tg

COPY start-container /usr/local/bin/start-container
COPY php.ini /usr/local/etc/php/conf.d/99-tg.ini
COPY xdebug.ini /usr/local/etc/php/conf.d/20-xdebug.ini

RUN rm -rf /usr/local/etc/php-fpm.d/* \
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

ADD php-fpm.d /usr/local/etc/php-fpm.d

RUN chmod +x /usr/local/bin/start-container \
    && apk add --no-cache sudo su-exec \
    && echo '%tg ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/tg

WORKDIR /home/tg/launcher

ENTRYPOINT ["start-container"]
```

Full error:
```
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c set -eux     && apk add --no-cache         zip         unzip         git         bash         shadow         imap-dev         freetype-dev         libmcrypt-dev     && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone     && apk add --no-cache --virtual .build-deps             $PHPIZE_DEPS             libgd             postgresql-dev             openldap-dev             libjpeg-turbo-dev             libpng-dev             libzip-dev             libxml2-dev             libx11-dev             libwebp-dev     && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp     && docker-php-ext-configure ldap --with-ldap-sasl     && docker-php-ext-install -j$(nproc) gd bcmath pgsql imap zip soap intl ldap pdo_mysql     && pecl install memcache xdebug msgpack igbinary redis mcrypt apcu mongodb imagick     && docker-php-ext-enable memcache xdebug msgpack igbinary redis mcrypt apcu mongodb imagick     && apk del --no-network .build-deps     && apk add --no-cache         libpng         libjpeg         libwebp         libx11         libc-utils         libical         libldap         libpq         libzip     && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer]: exit code: 1
```

docker-compose:
```yaml
version: "3.7"

services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
      args:
        XDEBUG: "${APP_DEBUG}"
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: teamgate/backend
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - ".:/home/tg/web"
      - "./data:/home/tg/data"
      - teamgate_shared:/home/tg/sock
    networks:
      - teamgate
    depends_on:
      - mysql
      - redis
      - memcached
      - mailhog

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: teamgate/frontend
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - ".:/home/tg/crm"

  launcher:
    build:
      context: ./dependencies/launcher/docker/backend
      dockerfile: Dockerfile
      args:
        XDEBUG: "${APP_DEBUG}"
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: teamgate/launcher
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - "./dependencies/launcher:/home/tg/launcher"
      - teamgate_shared:/home/tg/sock
    networks:
      - teamgate
    depends_on:
      - mysql
      - redis
      - memcached
      - mailhog

  landing:
    build:
      context: ./dependencies/landing/docker/backend
      dockerfile: Dockerfile
      args:
        XDEBUG: "${APP_DEBUG}"
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: teamgate/landing
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - "./dependencies/launcher:/home/tg/landing"
      - teamgate_shared:/home/tg/sock
    networks:
      - teamgate
    depends_on:
      - mysql
      - redis
      - memcached
      - mailhog

  webserver:
    build:
      context: ./docker/webserver
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: teamgate/webserver
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - "./docker/webserver/templates:/etc/nginx/templates"
      - ".:/home/tg/web"
      - "./dependencies/launcher:/home/tg/launcher"
      - teamgate_shared:/home/tg/sock
    networks:
      teamgate:
        aliases:
          - launcher.teamgate.local
          - se.teamgate.local
          - dev.teamgate.local
          - "*.teamgate.local"
    depends_on:
      - backend
      - launcher

  mysql:
    image: "mariadb:10.6"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - teamgate

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "teamgate_redis:/data"
    networks:
      - teamgate

  memcached:
    image: 'memcached:alpine'
    ports:
      - '11211:11211'
    networks:
      - teamgate

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - teamgate

  mongo:
    image: mongo
    restart: always
    volumes:
      - "./data/mongodb/db:/data/db"
      - "./data/mongodb/configdb:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  teamgate:
    driver: bridge
volumes:
  teamgate_redis:
    driver: local
  teamgate_shared:
    driver_opts:
      type: tmpfs
      o: "size=512M,nr_inodes=10k,mode=0755,uid=${WWWUSER},gid=${WWWGROUP}"
      device: tmpfs
```

```
❯ docker -v
Docker version 20.10.8, build 3967b7d
```

Using latest BigSur M1 Macbook Pro 13.3 Inch 16GB
