### ISSUE TITLE
Using target platform as a variable in compose file.

### ISSUE THREAD

**Issue by wasabii** [docker/buildx#792]
I have an existing compose file which is somewhat like this:

```
services:
  asd-scheduler:
    image: asd/scheduler:${VERSION}
    build:
      context: ${BUILDDIR}/docker/${TARGETPLATFORM}/tmp/asdasd
      dockerfile: ${ROOTDIR}/src/asdasd/Dockerfile
```

The point here is that when building for a certain platform, I need to obtain completely different application files. So I change the context based on what platform I'm building for. Prevents copying a massive amount of useless stuff in.

Since buildx bake can now do this all on it's own, building for mulitple platforms, how can I have a variable available in this way? Is there any variable that can be used inside the compose file syntax that obtains the current target platform as known to bake?
