### ISSUE TITLE
buildx build writes to stderr, even when successful

### ISSUE THREAD

**Issue by lukewis** [docker/buildx#802]
# Expected behavior
buildx should not write to stderr during a successful build

# Steps to reproduce

I'm using Azure Pipelines to build images using buildx.  Azure Pipelines has a property to fail the build if a step writes to stderr.  
- [Repo that reproduces the issue](https://github.com/lukewis/buildx/tree/bug/stderr)
- [Pipeline that illustrates the issue](https://dev.azure.com/figtreesoftware/Public/_build/results?buildId=1027&view=results)
```
trigger:
  - main
  - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildDocker
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false

    - script: ./build.sh
      displayName: Build & Push Image
      # buildx writes to stderr
      # failOnStderr: true
```
