### ISSUE TITLE
GitHub action fails with: rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by cgreening** [docker/buildx#808]
```
level=error msg="(*service).Write failed" error="rpc error: code = Canceled desc = context canceled" 
```

I've tried with the latest version of buildx and it still doesn't seem to work.
yaml:

```
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: build image
      uses: docker/build-push-action@v2
      with:
        context: ${{inputs.path}}
        tags: "XXXX"
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
```
