### ISSUE TITLE
Help automate verifying base images during a build

### ISSUE THREAD

**Issue by DennisDenuto** [docker/buildx#871]
As suggested by @AkihiroSuda in https://github.com/moby/moby/issues/43044 creating issue here.

**Description**

When building an image using a `Dockerfile` I would like to verify the base images used *before* performing a build. I would also like to use an image verification tool of my choice. (Whether that is notary, cosign, gpg etc)

Currently, I am left parsing out the `FROM` statements from the `Dockerfile`, which may require interpolating build-arguments used in the actual `docker build` command.

It would be useful in automation if either:
1) there was a sub-command `docker builder inspect` to output the list of base images in the provided `Dockerfile`
or
2) docker build accepts configuration that can verify a base image name (with wildcard globbing) with a specific command. If a base image is missing a mapping, then docker build could print a warning message to the user.  
`docker build -t img1 --verify verify.yaml .`

verify.yaml:
```yaml
- ref: repo1/a-base-image:*
  verifyCommand: image-verify-tool -key ${key} ${{ .ref }}
- ref: repo2/*
  verifyCommand: another-verify-tool ${{ .ref }}
```
