### ISSUE TITLE
Set mirror as environment variable

### ISSUE THREAD

**Issue by hansbogert** [docker/buildx#896]
Currently I have the following config:

```
debug = true

[registry."docker.io"]
  mirrors = ["mymirror.com:5000"]

[registry."mymirror.com:5000"]
  http = true
```

However this is tedious to include in every project's pipeline, is there a way to force this from the environment in my case a gitlab pipeline?

The actual gitlab job definition is something like:

```
build:
  image:
    name: maniator/dind-buildx
    entrypoint: [docker-entrypoint.sh]
  stage: build
  script:
  - docker context create defaultx
  - docker buildx create defaultx --name d1 --use --config=cicd/buildx.toml
  - docker buildx bake -f bake.hcl -f docker-compose.yml -f docker-compose.build.yml  --push
```

I hope to eliminate the `--config=cicd/buildx.toml` part and keep my gitlab-ci file agnostic to site specific config like a mirror.
